### ISSUE TITLE
can this plugin be used to profile unit tests?

### ISSUE THREAD

**Issue by tedder** [pledbrook/grails-profiler#6]
..and if so, how? It doesn't seem to be possible.

**Comment by tomdcc** [comment]
Not really - it uses interceptors and other runtime stuff that won't exist when running unit tests.

You could try the [miniprofiler-jvm](https://github.com/tomdcc/miniprofiler-jvm) project for profiling that should work when unit tests are running, and there's an associated [grails plugin](https://github.com/tomdcc/grails-miniprofiler) though to be honest I haven't tested it on grails since about 2.3, so it may well have bitrotted a fair bit by this point.
